# Generated by Django 2.1.3 on 2018-11-23 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
