# Generated by Django 2.1.3 on 2018-11-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app1', '0004_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('cno', models.IntegerField()),
                ('clas', models.CharField(max_length=150)),
                ('uname', models.CharField(max_length=150)),
                ('upass', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
    ]
