# Generated by Django 2.1.3 on 2018-11-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facultyuploading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title1', models.CharField(max_length=50)),
                ('Title2', models.CharField(max_length=50)),
                ('clas', models.CharField(max_length=150)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
