# Generated by Django 2.1.3 on 2018-11-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_attedence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attedence',
            name='apr',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='attedence',
            name='aug',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='attedence',
            name='dec',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='attedence',
            name='feb',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='attedence',
            name='jan',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='attedence',
            name='july',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='attedence',
            name='june',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='attedence',
            name='mar',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='attedence',
            name='may',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='attedence',
            name='nov',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='attedence',
            name='oct',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='attedence',
            name='sep',
            field=models.IntegerField(),
        ),
    ]
